sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            sonata.admin.group.dashboard:
#                on_top: true
                label: 'Dashboard'
                label_catalogue: messages
                icon: '<i class="fa fa-dashboard"></i>'
                items:
                    - route: sonata_admin_dashboard
                      label: Dashboard

                    - Sonata\MediaBundle\Admin\ORM\MediaAdmin

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
